### ISSUE TITLE
How can i use it for Proxy

### ISSUE THREAD

**Issue by garrylachman** [MicroMinion/1tp#28]
Hi,
How can i use it for proxy server behind a nat?

Thanks #

**Comment by nicojanssens** [comment]
hi @garrylachman 

What exactly do you want to accomplish?

1tp can be used to establish connections between peers located behind NAT boxes. It will use a WebRtc or a TURN data channel to relay data between both peers. I'm currently also integrating our [UdpHolePunching](https://github.com/MicroMinion/udp-hole-puncher-js) lib such that we have a cheaper alternative to traverse NAT devices. But that is WiP.

So if NAT traversal would be taken care of, would you still need a proxy server? Maybe for load-balancing purposes? 

Btw, if you'd like to use 1tp in combination with a proxy server, then the latter must also speak 1tp -- otherwise it won't understand our 1tp signaling messages. So that implies you'll have to modify this proxy server. Unless if I would add a tuntap tunnel interface above 1tp to expose its endpoints as a network interface.
